name: Generate Snake Game

on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@master
        id: snake_generator
        with:
          github_user_name: FLAranoHerrera
          gif_out_path: output/github-contribution-grid-snake.gif
          svg_out_path: output/github-contribution-grid-snake.svg

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Generate Snake Game'
          add: 'output/github-contribution-grid-snake.*'
